name: Main

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  testAndBuild:
    name: "Test and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: nr lint

      - run: nr test
        env:
          CI: "true"

      - run: nr build


      - run: pnpm publish --access public --no-git-checks
        if: contains(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
