name: Main

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  testAndBuild:
    name: "Test and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: nr lint

      - run: nr test
        env:
          CI: "true"

      - run: nr build

      - name: Upload artifacts
        if: contains(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: ./dist

  publishGitHub:
    name: "Publish to GitHub Packages"
    runs-on: ubuntu-latest
    needs: testAndBuild
    if: contains(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}
      - uses: actions/download-artifact@v8
        with:
          name: artifacts
          path: ./dist

      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

  publishNpm:
    name: "Publish to npm"
    runs-on: ubuntu-latest
    needs: testAndBuild
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: artifacts
          path: ./dist

      - name: Publish package
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          pnpm publish --access public
